### ISSUE TITLE
light don't change color or brightness with template automation

### ISSUE THREAD

**Issue by Rehbinski** [mion00/color-temperature-light-mixer#13]
## System Information

version | core-2024.7.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1391
Downloaded Repositories | 33
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 27.5 GB
disk_used | 7.4 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (18.0.0), Home Assistant Google Drive Backup (0.112.1), Samba share (12.3.1), File editor (5.8.0), Zigbee2MQTT (1.39.0-1), Mosquitto broker (6.4.1), Let's Encrypt (5.0.22)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 20
views | 17
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 2. Juli 2024 um 05:01
-- | --
current_recorder_run | 12. Juli 2024 um 09:26
estimated_db_size | 602.22 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/mion00/color-temperature-light-mixer/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

Brightness and color don't, with a template automation.

service: light.turn_on
data:
  brightness_pct: {{ state_attr('switch.adaptive_lighting_test_2', 'brightness_pct') | int }}
  kelvin: {{ state_attr('switch.adaptive_lighting_test_2', 'color_temp_kelvin') | int }}
target:
  entity_id: light.testlicht

### Reproduction steps

1. turn light off
2. set automation with template
3. start automation
4. don't change color from state_attr
...

### Debug logs

```text
n/a
```

**Comment by Matsonson** [comment]
Did you get anywhere with this? I have Adaptive Lighting installed and it seems its never able to change the light color or brightness. The CCT LED strip is only turned on for a couple of minutes at a time. 

After testing manually running the "Light: Turn on" action, the initial startup is always the same no matter what I do.

After enabling logging I found this:

2024-12-29 21:07:19.225 DEBUG (MainThread) [custom_components.color_temperature_light_mixer.light] Stairs light strip: turn on with params: {'color_temp': 399, 'color_temp_kelvin': 2504, 'brightness': 153}
2024-12-29 21:07:19.225 DEBUG (MainThread) [custom_components.color_temperature_light_mixer.helper] Computing brightness for temp: 3000, bright: 153, priority: MIXED
2024-12-29 21:07:19.226 DEBUG (MainThread) [custom_components.color_temperature_light_mixer.helper] Computed brightness, c: 0, w: 306
2024-12-29 21:07:19.227 DEBUG (MainThread) [custom_components.color_temperature_light_mixer.helper] Computed new target_temperature: 167, target_brightness: 138
2024-12-29 21:07:19.227 DEBUG (MainThread) [custom_components.color_temperature_light_mixer.helper] Computed brightness, c: 255, w: 21
2024-12-29 21:07:19.228 DEBUG (MainThread) [custom_components.color_temperature_light_mixer.light] Stairs light strip: forward turn_on: {'entity_id': 'light.shellyplusrgbwpm_08a6f773136c_light_0'} {'color_temp_kelvin': 2504, 'brightness': 255}
2024-12-29 21:07:19.228 DEBUG (MainThread) [custom_components.color_temperature_light_mixer.light] Stairs light strip: forward turn_on: {'entity_id': 'light.shellyplusrgbwpm_08a6f773136c_light_1'} {'color_temp_kelvin': 2504, 'brightness': 21}
2024-12-29 21:07:19.373 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aioshelly/rpc_device/wsrpc.py", line 366, in _rx_msgs
    self.handle_frame(RPCSource.CLIENT, frame)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aioshelly/rpc_device/wsrpc.py", line 315, in handle_frame
    self._on_notification(source, method, params)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aioshelly/rpc_device/device.py", line 146, in _on_notification
    mergedicts(self._status, params)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aioshelly/rpc_device/device.py", line 59, in mergedicts
    mergedicts(dest[k], v)
    ~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aioshelly/rpc_device/device.py", line 59, in mergedicts
    mergedicts(dest[k], v)
    ~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aioshelly/rpc_device/device.py", line 58, in mergedicts
    if k in dest and type(v) is dict:  # - only accepts `dict` type
       ^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable


This lead me to believe Shelly was the culprit. I changed my Shelly RGBW2 from RGBW mode to Lights mode **after** pairing it with home assistant. This was found [here](https://community.home-assistant.io/t/shelly-duo-rgbw-light-generates-error/333001/2) to be the issue and it can be fixed by removing the Shelly integration and adding it again. 

Edit: My issues seems to be due to Adaptive Lighting. After more digging I noticed this integration controls the lights by turning them on. Which is grabbed by the Adaptive Lighting trying to set the color temperature according to the time of day. Adaptive Lighting log shows that it tries to set the temperature for each channel individually, which of course fails since the outputs are brightness only.

**Comment by Matsonson** [comment]
Hmm. It didn't seem to start working even I first thought. I get this from the "Light: turn on" event when I try to turn on the Shelly light directly.

`Failed to perform the action light.turn_on. Call RPC for shellyplusrgbwpm-08a6f773136c Light 1 connection error, method: Light.Set, params: {'id': 1, 'on': True, 'brightness': 1, 'transition_duration': 1.0}, error: DeviceConnectionError()`

If I remove the Color Temperature Light Mixer, I get no errors and the Shelly is able to control the light just fine. For some reason the Shelly integration doesn't like this one.

**Comment by Coliinnn** [comment]
> Edit: My issues seems to be due to Adaptive Lighting. After more digging I noticed this integration controls the lights by turning them on. Which is grabbed by the Adaptive Lighting trying to set the color temperature according to the time of day. Adaptive Lighting log shows that it tries to set the temperature for each channel individually, which of course fails since the outputs are brightness only. 

Seeing the edit in your post, I was wondering if you ended up finding a method to make adaptive lighting work with this integration? Or do you think that it is just not possible to combine the two integrations?

**Comment by Matsonson** [comment]
> Seeing the edit in your post, I was wondering if you ended up finding a method to make adaptive lighting work with this integration? Or do you think that it is just not possible to combine the two integrations?

I have my light automations mostly on NodeRed and I thought it would be easier to mock adaptive lighting for the CCT Led strip in the node red directly. I ended up making a sub node that calculates the color temp and brightness and calls service>light on for both channels individually according to the calculated values. The functions are somewhat the same the adaptive lighting uses.

I can share the node red script but unfortunately I didn't dare for a more sophisticated way as I'm not too confident with my python and have yet to make any integrations myself.

[flows.json](https://github.com/user-attachments/files/18638277/flows.json)

Hope this helps.

**Comment by Coliinnn** [comment]
@Matsonson Thanks a lot for sharing this! Great that you were able to find something of a solution, at least.
